[package]
name = "wasmcloud_interface_mlcompute"
version = "0.1.0"
description = "Interface library for the mlcompute converter capability, "
authors = [ "" ]
edition = "2021"
license = "Apache-2.0"

# when publishing to crates.io, freeze src by omitting build.rs
exclude = [ "build.rs" ]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
serde = { version = "1.0" , features = ["derive"] }
serde_bytes = "0.11.5"
wasmbus-rpc = "0.7"

[dev-dependencies]
base64 = "0.13"

# build-dependencies needed for build.rs
[build-dependencies]
weld-codegen = "0.3"

