[package]
name = "inferenceapi"
version = "0.1.0"
authors = [ "" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "inferenceapi"

[dependencies]
async-trait = "0.1"
futures = "0.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
form_urlencoded = "1.0"
wasmbus-rpc = "0.7"
wasmcloud-interface-logging = "0.4"
wasmcloud-interface-httpserver = "0.4"
wasmcloud_interface_mlinference = { path="../../interfaces/mlinference/rust" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
