[package]
    name = "mlinference"
    version = "0.1.0"
    edition = "2021"
    resolver = "2"

[dependencies]
    async-trait = "0.1"
    base64 = "0.13"
    log = "0.4"
    wasmcloud_interface_mlinference = { path="../../interfaces/mlinference/rust" }
    wasmbus-rpc = "0.7.5"
    serde = { version = "1.0" , features = ["derive"] }
    byteorder         = "1.4"
    thiserror         = "1.0"
    tokio = { version = "1", features = ["full"] }
    toml = "0.5"
    serde_json = "1.0"
    bindle = "0.8.0"
    ndarray           = "0.15"
    tract-onnx        = { version = "0.15.8" }
    tract-data        = "0.15.8"
    tract-linalg      = "0.15.8"

# test dependencies
[dev-dependencies]
    wasmcloud-test-util = "0.2.1"
    tokio = { version = "1.0", features = [ "full" ] }

[lib]
name = "wasmcloud_provider_mlinference"
path = "src/lib.rs"

[[bin]]
    name = "mlinference"
    path = "bin/main.rs"
