# mlinference Makefile

CAPABILITY_ID = "wasmcloud:example:mlinference"
NAME = "mlinference"
VENDOR = "Acme"
PROJECT = mlinference
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

