# configuration for mlinference test

# name of compiled binary (usually project name unless overridden in [[bin]]
# Required
bin_path = "target/release/mlinference"

# set RUST_LOG environment variable (default "info")
rust_log = "debug"

# set RUST_BACKTRACE (default: 0)
rust_backtrace = "1"

# nats should be running. Uncomment to override the default url
#nats_url = "0.0.0.0:4222"

# lattice prefix (default "default")
#lattice_rpc_prefix = "default"

# link name (default: "default")
#link_name = "default"

# name of contract under test
contract_id = "wasmcloud:example:mlinference"

# values here will be passed as config_b64
[values]
lazy_load = false
models = {zoo = { challenger = "enterprise.com/warpcore/1.1.0", champion = "enterprise.com/warpcore/1.0.0", flex = "enterprise.com/warpcore/1.2.0"}}