# configuration for mlinference test

# name of compiled binary (usually project name unless overridden in [[bin]]
# Required
bin_path = "target/release/mlinference"

# set RUST_LOG environment variable (default "info")
rust_log = "debug"

# set RUST_BACKTRACE (default: 0)
rust_backtrace = "1"

# nats should be running. Uncomment to override the default url
#nats_url = "127.0.0.1:4222"

# lattice prefix (default "default")
#lattice_rpc_prefix = "default"

# link name (default: "default")
#link_name = "default"

# name of contract under test
contract_id = "wasmcloud:mlinference"

# values here will be passed as config_b64
[values]
lazy_load = false

# works with serde_json
models = {zoo = { identity = "identity_model/0.2.0", plus3 = "plus3/0.1.0", mobilenetv27 = "mobilenetv2-7/0.1.0", squeezenetv117 = "squeezenetv1-1-7/0.1.0"}}


#[models]
#zoo = { identity = "identity_model/0.2.0", plus3 = "plus3/0.1.0"}
